name: PixelMOTD
version: ${project.version}
main: dev.mruniverse.pixelmotd.spigot.PixelMOTDBuilder
softdepend: [ProtocolLib, ViaVersion, PlaceholderAPI]
authors: [ MrUniverse44 ]
description: Simple MOTD System plugin
commands:
  pmotd:
    description: Main command of the plugin
  pixelmotd:
    description: Main command of the plugin