#   _____ _          _ __  __  ____ _______ _____
#   |  __ (_)        | |  \/  |/ __ \__   __|  __ \
#   | |__) |__  _____| | \  / | |  | | | |  | |  | |
#   |  ___/ \ \/ / _ \ | |\/| | |  | | | |  | |  | |
#   | |   | |>  <  __/ | |  | | |__| | | |  | |__| |
#   |_|   |_/_/\_\___|_|_|  |_|\____/  |_|  |_____/
#
#   Using version 9.2.3.1-SNAPSHOT
#   Author: MrUniverse44
#   SpigotMC Link: https://www.spigotmc.org/resources/37177/
#
settings:
  # Hex-Systems: IRIDIUMCOLORAPI, MINEDOWN
  # For BungeeCord try using MINEDOWN
  # Docs:
  # - MineDown: https://github.com/Phoenix616/MineDown/
  # - IridiumColorAPI: https://github.com/Iridium-Development/IridiumColorAPI
  hex-system-process: IRIDIUMCOLORAPI
  # This motd will appear when:
  #   - You don't have installed ProtocolLib
  #   - The player is running in a version before 1.16
  # values: DEFAULT, HEX
  default-priority-motd: "DEFAULT"
  # File Config Version, this prevents issues
  config-version: 4
  # Enable Check update when the plugin load
  update-check: true
  # Auto Download Updates
  auto-download-updates: true
  # Online servers w/ sub-servers system.
  # Usage: %variable_<key>%
  # Example: %variable_exampleName%
  online-variables:
    # Here you have two examples for CONTAINS mode and NAMES mode.
    # Modes: NAMES,CONTAINS
    exampleName:
      # Name: Name will check the name of all servers, if your list contains the name of X servers, size of all players
      # In these servers will be added to the online count of this variable.
      mode: NAMES
      values:
        - "hub1"
        - "hub2"
        - "hub3"
    exampleContains:
      # CONTAINS (Example): You have sub-servers for SkyWars minigame, all servers contains "swmap" in the name.
      # Example: swmap1,swmap2,swmap3,swmap4 and you want to get the online players count of these servers
      # Including the lobby players-count (swlobby1,swlobby2). This mode will check the name of all servers
      # with your values to get the online-size.
      mode: CONTAINS
      values:
        - "swmap"
        - "swlobby1"
  # Player Name system, usage: %player_<number>% system
  player-system:
    # Toggle this option
    toggle: true
    # This is for %player_<number>% variables, if you disable this variables will not work but the motd will load faster.
    # But if you want to use this, here is the system, They asked me to add this system, and it is because it is here.
  # Plugin language file, if you want to add your custom lang file you need put the name ("messages_<code>.yml") and in the language you put the code, example:
  # messages_en.yml | code: en | language: en
  # messages_es.yml | code: es | language: es
  # messages_jp.yml | code: jp | language: jp
  # messages_pl.yml | code: pl | language: pl
  language: en
  # This option is only for bungeecord!
  # Don't work in spigot version.
  # Variable: %status_<server>%
  server-status:
    toggle: false
    online: "&a&lONLINE"
    offline: "&c&lOFFLINE"
    intervals:
      online: 10
      offline: 10
      timeout: 500
  # Customize your event priority level, priorities: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST, Now on bungeecord!
  event-priority: HIGH
  # Customize your event priority level for blacklist & whitelist check: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST
  extras-event-priority: HIGH
  # Toggle the 1.16+ motd
  different-motd-for-116-or-higher: true
  # Toggle outdated-client motd system
  outdated-client-motd: true
  # Toggle outdated-server motd system
  outdated-server-motd: true
  # Toggle this option
  icon-system: true
  # Config your max-server-protocol and min-server-protocol for the check of the outdated-client and outdated-server.
  # You can see protocols here: https://minecraft.fandom.com/wiki/Protocol_version
  # Default protocol versions are 1.8 to 1.18
  max-server-protocol: 757
  min-server-protocol: 47
  # Toggle update-check for Alpha and Beta Versions
  check-alpha-updates: false
