#   _____ _          _ __  __  ____ _______ _____
#   |  __ (_)        | |  \/  |/ __ \__   __|  __ \
#   | |__) |__  _____| | \  / | |  | | | |  | |  | |
#   |  ___/ \ \/ / _ \ | |\/| | |  | | | |  | |  | |
#   | |   | |>  <  __/ | |  | | |__| | | |  | |__| |
#   |_|   |_/_/\_\___|_|_|  |_|\____/  |_|  |_____/
#
#   Using version 9.0.0-SNAPSHOT
#   Author: MrUniverse44
#   SpigotMC Link: https://www.spigotmc.org/resources/37177/
#
settings:
  # Enable Check update when the plugin load
  update-check: true
  # Auto Download Updates
  auto-download-updates: true
  # Update all fileStorage on plugin-reload-command to prevent issues:
  update-file-storage: true
  # Player Name system, usage: %player_<number>% system
  player-system:
    # Toggle this option
    toggle: true
    # The system will stop the call the variable to this max (Recommended a low number)
    # The max number will be the maximum, for example:
    # -  If the max is 10, the variable only will work to %player_10%, if you use
    # -  %player_11% this line will not be showed.
    # -  If the online player size is > than the max, the plugin will only show the online number.
    max: 10
  # Plugin language file, if you want add your custom lang file you need put the name ("messages_<code>.yml") and in the language you put the code, example:
  # messages_en.yml | code: en | language: en
  # messages_es.yml | code: es | language: es
  language: en
  # Customize your event priority level, priorities: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST (This option don't work on BungeeCord)
  event-priority: HIGH
  # Customize your event priority level for blacklist & whitelist check: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST
  extras-event-priority: HIGH
  # Toggle outdated-client motd system
  outdated-client-motd: true
  # Toggle outdated-server motd system
  outdated-server-motd: true
  # Toggle icon system of PixelMOTDBuilder
  icon-system: true
  # Config your max-server-protocol and min-server-protocol for the check of the outdated-client and outdated-server.
  # You can see protocols here: https://minecraft.fandom.com/wiki/Protocol_version
  # Default protocol versions are 1.8 to 1.17
  max-server-protocol: 755
  min-server-protocol: 47
  # Toggle update-check for Alpha and Beta Versions
  check-alpha-updates: false
