#   _____ _          _ __  __  ____ _______ _____
#   |  __ (_)        | |  \/  |/ __ \__   __|  __ \
#   | |__) |__  _____| | \  / | |  | | | |  | |  | |
#   |  ___/ \ \/ / _ \ | |\/| | |  | | | |  | |  | |
#   | |   | |>  <  __/ | |  | | |__| | | |  | |__| |
#   |_|   |_/_/\_\___|_|_|  |_|\____/  |_|  |_____/
#
#   Using version 9.0.0-SNAPSHOT
#   Author: MrUniverse44
#   SpigotMC Link: https://www.spigotmc.org/resources/37177/
#
settings:
  # Enable Check update when the plugin load
  update-check: true
  # Plugin language file, if you want add your custom lang file you need put the name ("messages_<code>.yml") and in the language you put the code, example:
  # messages_en.yml | code: en | language: en
  # messages_es.yml | code: es | language: es
  language: en
  # Customize your event priority level, priorities: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST
  event-priority: HIGH
  # Toggle outdated-client motd system
  outdated-client-motd: true
  # Toggle outdated-server motd system
  outdated-server-motd: true
  # Config your max-server-protocol and min-server-protocol for the check of the outdated-client and outdated-server.
  # You can see protocols here: https://minecraft.fandom.com/wiki/Protocol_version
  max-server-protocol: 755
  min-server-protocol: 47
  # Toggle update-check for Alpha and Beta Versions
  check-alpha-updates: false
  # Toggle Events,if this option is disabled, events will not load and variables will not work. Recommended: false, if you have +1000 users.
  # Only enable this option when you have an event running.
  events-toggle: false
  # Customize your own events
  events:
    # This is the default event, to add more events only copy and paste it
    # (obviously replacing the name 'exampleEvent' with another name)
    exampleEvent:
      eventName: Example Event
      eventDate: 12/21/21 23:59:00
      TimeZone: ECT
      format-Type: FIRST
      endMessage: '&cThe event finished.'
  # Time Option
  timer:
    weeks: weeks
    week: week
    days: days
    day: day
    minutes: minutes
    minute: minute
    seconds: seconds
    second: second