#   _____ _          _ __  __  ____ _______ _____
#   |  __ (_)        | |  \/  |/ __ \__   __|  __ \
#   | |__) |__  _____| | \  / | |  | | | |  | |  | |
#   |  ___/ \ \/ / _ \ | |\/| | |  | | | |  | |  | |
#   | |   | |>  <  __/ | |  | | |__| | | |  | |__| |
#   |_|   |_/_/\_\___|_|_|  |_|\____/  |_|  |_____/
#
#   Using version 9.2.0-SNAPSHOT
#   Author: MrUniverse44
#   SpigotMC Link: https://www.spigotmc.org/resources/37177/
#
settings:
  # File Config Version, this prevents issues
  config-version: 1
  # Enable Check update when the plugin load
  update-check: true
  # Auto Download Updates
  auto-download-updates: true
  # Player Name system, usage: %player_<number>% system
  player-system:
    # Toggle this option
    toggle: true
    # This is for %player_<number>% variables, if you disable this variables will not work but the motd will load more faster.
    # But if you wanna use this, here is the system, They asked me to add this system and it is because it is here.
  # Plugin language file, if you want add your custom lang file you need put the name ("messages_<code>.yml") and in the language you put the code, example:
  # messages_en.yml | code: en | language: en
  # messages_es.yml | code: es | language: es
  language: en
  # This option is only for bungeecord!
  # Don't work in spigot version.
  # Variable: %status_<server>%
  server-status:
    toggle: false
    online: "&a&lONLINE"
    offline: "&c&lOFFLINE"
    intervals:
      online: 10
      offline: 10
      timeout: 500
  # Customize your event priority level, priorities: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST (This option don't work on BungeeCord)
  event-priority: HIGH
  # Customize your event priority level for blacklist & whitelist check: MONITOR-LOWEST-LOW-NORMAL-HIGH-HIGHEST
  extras-event-priority: HIGH
  # Toggle outdated-client motd system
  outdated-client-motd: true
  # Toggle outdated-server motd system
  outdated-server-motd: true
  # Toggle this option
  icon-system: true
  # Config your max-server-protocol and min-server-protocol for the check of the outdated-client and outdated-server.
  # You can see protocols here: https://minecraft.fandom.com/wiki/Protocol_version
  # Default protocol versions are 1.8 to 1.17
  max-server-protocol: 756
  min-server-protocol: 47
  # Toggle update-check for Alpha and Beta Versions
  check-alpha-updates: false
